apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSzllM0h3NGZZTDR3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBME1EUXhNVEkyTURCYUZ3MHpOVEEwTURJeE1UTXhNREJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUREVDdUR3RaVFBFb2JGN1c1bUQrd21HV0M5R1RXU1hzaS82M3pqWUJodGtaaWoyaytMRlRJa0o0b0wKUnlQRTZJMUgyVlNzZWVKWjFRVzZJcnN0SFpqMHN1em9Ra0YwczhrbDN6S0EzUE54UGNWSFFvVWdCcVNVQmZ0SgpXZkVmcmR3UlNZL2JxbisxT3NkcXFiUlUvK2tKakl3anlzMVNuMlFnUENFYm96bE1KWm9rREZLWGc4cE4yUmkyCkNoY2llaTlsaUhGc1ZzcmNkMW1PbG1EVzBZWHhoK3UxazUvVXV3STYrOGhZUDNVbGlZc1ZzZUY4RmhvQWNlV1gKVk9RYm12RnhmdlBObnh2YTBKY0RyVW1GeGxSb0VPdWxpd05zOThkd0lHSTNvdFhNZlFZaGhYMmFqSGtWVmovdwppQjMzeGNIQlRtSUptUTd5Tm5JQXJ6bERvb0FoQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRM1NUcUpRdVptM1RKNHFFMUg4TDI2N1YzYjhqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQjZtRGRMMzdtVgpUdVFJWjljY2txVDZndk83bFNNV1JmbXd3UjVOWmJqWllLWVliS1AzclVUTk9HaGxMcW5pS0loOXBIb1VqZUlJCkNaMjRRQnozSUV2K3JHK05XOHQycGhhV3hnOXAvUEdTYTFFMitqc0Erd3A4R2p1SWIzdU5LZHZ1SVRmQm9qRlkKc3U4T0IxL3lybDk0V3FYWEdoSWtCeWtocGJHMjlNZWYxQVY1SE1QZEszQmd5QTZ3SENJSVo1ZXg2dWwvenNpZgpCTUJIaVRPNWF5bFVsNWdLdW9zRUVWcW1tUGU4OWZGZktnOVRwM2FBNzJQSUV5bWh5S2JzSnYrRnhLWmdJLy9xCmkxSG5DckFDVjFEc3pZZmVhRUlSNDFEWWNlaldmNTVkYnkwYnltSWY3VjRLT2g1SHhnZnA4UXpCUWtyYXhZQzgKaE5rYkwvN1hDdVBWCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://E54EA3C2886D2946EC36E97BBCF4F84F.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:778900843334:cluster/eks-cluster
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:778900843334:cluster/eks-cluster
    user: arn:aws:eks:us-east-1:778900843334:cluster/eks-cluster
  name: arn:aws:eks:us-east-1:778900843334:cluster/eks-cluster
current-context: arn:aws:eks:us-east-1:778900843334:cluster/eks-cluster
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:778900843334:cluster/eks-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - eks-cluster
      command: aws
      env:
      - name: AWS_PROFILE
        value: personal
