- name: Install Dockerapt
  hosts:
    - control_plane
    - workers
  gather_facts: false
  become: true
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - docker.io
        update_cache: true
    - name: Create docker group
      ansible.builtin.group:
        name: docker
        state: present
    - name: Add user to docker group
      ansible.builtin.user:
        append: true
        name: "{{ ansible_user }}"
        groups: docker
    - name: Sets Docker cgroup driver to systemd
      ansible.builtin.copy:
        content: |
          {
            "exec-opts": ["native.cgroupdriver=systemd"],
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "100m"
            },
            "storage-driver": "overlay2"
          }
        dest: /etc/docker/daemon.json
    - name: Create systemd directory
      ansible.builtin.file:
        path: /etc/systemd/system/docker.service.d
        state: directory
    - name: Restart Docker
      ansible.builtin.systemd:
        name: docker
        state: restarted
        daemon_reload: true
