- name: Install Kubernetes binaries
  hosts:
    - masters
    - workers
  gather_facts: false
  become: true
  tasks:
    - name: Add Kubernetes GPG key
      ansible.builtin.apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    - name: Add Kubernetes repo
      ansible.builtin.apt_repository:
        repo: 'deb https://apt.kubernetes.io/ kubernetes-xenial main'
    - name: Install Kubernetes packages
      ansible.builtin.apt:
        name:
          - kubelet={{ kube_version }}-00
          - kubeadm={{ kube_version }}-00
          - kubectl={{ kube_version }}-00
        update_cache: true

- name: Init master
  hosts: master
  become: true
  tasks:
    - name: Creates config.yaml for kubeadm
      ansible.builtin.template:
        src: kubeadm-config.yaml.j2
        dest: config.yaml
        mode: '0440'
    - name: Copy policy.yaml
      ansible.builtin.copy:
        src: kubernetes
        dest: /etc
        mode: '0400'
    - name: Run Kubeadm
      ansible.builtin.command: kubeadm init --config config.yaml
      register: kubeadm_init
      args:
        creates: /etc/kubernetes/admin.conf
    - name: Kubeadm init output
      ansible.builtin.debug:
        var: kubeadm_init.stderr_lines
    - name: Get Kubernets join cluster command
      ansible.builtin.command: kubeadm token create --print-join-command
      changed_when: false
      register: join_cmd
    - name: Export join command
      ansible.builtin.set_fact:
        join_cmd: "{{ join_cmd.stdout }}"

- name: Deploy Container Network
  import_playbook: cni-calico.yaml
  # import_playbook: cni-flannel.yaml

- name: Join master
  hosts: workers
  gather_facts: false
  become: true
  tasks:
    - name: Joining cluster
      ansible.builtin.command: "{{ hostvars['master'].join_cmd }}"
      changed_when: false

- name: Updates local kubectl config
  hosts: master
  gather_facts: false
  tasks:
    - name: Copy admin.conf to localhost
      become: true
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: "{{ lookup('env', 'HOME') }}/.kube/{{ kube_clustername }}.config"
        flat: true
