- name: Install Kubernetes binaries
  hosts:
    - control_plane
    - workers
  gather_facts: false
  become: true
  tasks:
    - name: Add Kubernetes GPG key
      ansible.builtin.apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v{{ kube_version | regex_replace('^(\d+\.\d+)\.\d+', '\1') }}/deb/Release.key
    - name: Add Kubernetes repo
      ansible.builtin.apt_repository:
        repo: deb https://pkgs.k8s.io/core:/stable:/v{{ kube_version | regex_replace('^(\d+\.\d+)\.\d+', '\1') }}/deb/ /
    - name: Install Kubernetes packages
      ansible.builtin.apt:
        name:
          - kubelet={{ kube_version }}-*
          - kubeadm={{ kube_version }}-*
          - kubectl={{ kube_version }}-*
        update_cache: true
    - name: Gets full hostname
      ansible.builtin.command: hostname -f
      register: full_hostname
      changed_when: true


- name: Init controller
  hosts: control_plane
  become: true
  tasks:
    - name: Creates config.yaml for kubeadm
      ansible.builtin.template:
        src: kubeadm-init-config.yaml.j2
        dest: config.yaml
        mode: '0440'
    - name: Copy policy.yaml
      ansible.builtin.copy:
        src: kubernetes
        dest: /etc
        mode: '0400'
    - name: Run Kubeadm
      ansible.builtin.command: kubeadm init --config config.yaml
      register: kubeadm_init
      args:
        creates: /etc/kubernetes/admin.conf
    - name: Makes kubeconfig available to all
      ansible.builtin.file:
        path: /etc/kubernetes/admin.conf
        mode: 0644
    - name: Sets KUBECONFIG
      ansible.builtin.lineinfile:
        dest: "/etc/environment"
        line: "KUBECONFIG=/etc/kubernetes/admin.conf"
    - name: Kubeadm init output
      ansible.builtin.debug:
        var: kubeadm_init.stderr_lines
    - name: Create a kubeadm bootstrap token
      command: kubeadm token create
      register: bootstrap_token

- name: Deploy GatewayAPI CRDs
  hosts: controller
  gather_facts: false
  tasks:
  - ansible.builtin.command: kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.1/experimental-install.yaml --kubeconfig=/etc/kubernetes/admin.conf

- name: Deploy Container Network
  import_playbook: cni-{{ cni }}.yaml

- name: Join control plane
  hosts: workers
  gather_facts: false
  become: true
  tasks:
    - name: Creates config.yaml for kubeadm
      ansible.builtin.template:
        src: kubeadm-join-config.yaml.j2
        dest: config.yaml
        mode: '0440'
    - name: Joining cluster
      ansible.builtin.command: "kubeadm join --config config.yaml"
      changed_when: false

- name: Updates local kubectl config
  hosts: control_plane
  gather_facts: false
  tasks:
    - name: Copy admin.conf to localhost
      become: true
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: "{{ lookup('env', 'DATA_DIR') }}/config"
        flat: true
