- name: Wait for machines to start
  hosts: all
  gather_facts: false
  tasks:
    - name: Waiting...
      ansible.builtin.wait_for_connection:
        timeout: 1200

- name: Update OS
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: full
        update_cache: true
