- name: Wait for machines to start
  hosts: all
  gather_facts: false
  tasks:
    - name: Waiting...
      ansible.builtin.wait_for_connection:
        timeout: 1200

- name: Update OS
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: full
        update_cache: true
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ ansible_host }}"
    - name: Set /etc/hostname
      ansible.builtin.copy:
        content: "{{ ansible_host }}"
        dest: /etc/hostname
        mode: '0644'
