/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package datadog.lbe.kafka.client;

public class App {

    public static void main(String[] args) {
        String bootstrap = System.getenv().get("APP_KAFKA_BOOTSTRAP");
        switch (System.getenv().getOrDefault("APP_MODE", "EMPTY").toLowerCase()) {
            case "producer":
                new Producer(bootstrap, System.getenv().get("APP_TOPIC")).run();
                break;
            case "consumer":
                new Consumer(bootstrap, System.getenv().get("APP_TOPIC")).run();
                break;
            case "bridge":
                new Bridge(bootstrap, System.getenv().get("APP_BRIDGE")).run();
                break;
            default:
                System.err.println("Invalid mode");
                System.exit(1);
        }
    }
}
